version: "3"

services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - PASSWORD=${PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
    volumes:
      - ./config:/config
      - ./data:/app
    networks:
        - default
    ports:
      - 9050:8443


networks:
  default:
    external:
      name: docker-network