version: "3"
services:
  mysql:
    image: mysql:5
    container_name: snipe_mysql
    restart: always
    volumes:
      - /home/dockers/snipeit/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Sn1pe1t
      - MYSQL_USER=snipe_usr
      - MYSQL_PASSWORD=Sn1pe1t
      - MYSQL_DATABASE=snipe_it
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - /home/dockers/snipeit/config:/config
    environment:
      - APP_URL=192.168.1.202:9010
      - MYSQL_PORT_3306_TCP_ADDR=localhost
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=Sn1pe1t
      - PGID=1000
      - PUID=1000
      - timezone=Pacific\Auckland
    ports:
      - "9010:80"