version: "3.5"

services:

 snipeit:
    container_name: snipeit
    restart: always
    image: snipe/snipe-it:latest
    volumes:
      - ./cert:/var/lib/snipeit/ssl
      - ./script/init.sh:/usr/local/bin/init.sh
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_KEY: "<<YOUR GENERATED KEY HERE>>"
      APP_URL: "https://asset.technicalkiwi.com"
      APP_TIMEZONE: "Pacific/Auckland"
      APP_LOCALE: "en"
      MYSQL_ROOT_PASSWORD: "Dino1"
      MYSQL_DATABASE: "snipeit_app"
      MYSQL_USER: "snipeit_user"
      MYSQL_PASSWORD: "Snipe1t"
      MYSQL_PORT_3306_TCP_ADDR: "mysql"
      MAIL_PORT_587_TCP_ADDR: "<<FQDN OF YOUR MAIL SERVER>>"
      MAIL_PORT_587_TCP_PORT: "587"
      MAIL_ENV_FROM_ADDR: "alerts@technicalkiwi.com"
      MAIL_ENV_FROM_NAME: "Snipe It Alerts"
      MAIL_ENV_ENCRYPTION: "tls"
      MAIL_ENV_USERNAME: "<<MAIL SERVER LOGIN>>"
      MAIL_ENV_PASSWORD: "<<MAIL SERVER PASSWORD>>"
    links:
      - snipeit_db:mysql
    ports:
      - 9015:80
      - 9016:443
    command:
      - init.sh

 snipeit_db:
    container_name: snipeit_db
    restart: always
    image: mysql:5.6
    volumes:
      - ./snipeit_db:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: "Dino1"
       MYSQL_DATABASE: "snipeit_app"
       MYSQL_USER: "snipeit_user"
       MYSQL_PASSWORD: "Snipe1t"
    ports:
      - 3306:3306