#Template for Docker Compose Version 3
version: '3'

services:
  Leantime:
    image: leantime/leantime
    restart: always
    container_name: Leantime
    ports: 
      - 9018:80
      - 9019:9000

    environment:
      - LEAN_DB_HOST: '10.3.27.90'
      - LEAN_DB_USER: 'lean'
      - LEAN_DB_PASSWORD: 'lean'
      - LEAN_DB_DATABASE: 'leantime'

    networks:
      - default

networks:
  default:
    external:
      name: docker-network
