version: '3'
services:

    cells:
      image: pydio/cells:latest
      restart: always
      ports: 
        - 9020:8080
        - 9021:80
        - 9022:443

      environment:
          - CELLS_BIND=http://192.168.10.42:9020
          - CELLS_EXTERNAL=http://192.168.10.42:9020
      volumes: 
          - ./data/cellsdir:/var/cells
          - ./data/data:/var/cells/data

    # MySQL image with a default database cells and a dedicated user pydio
    mysql:
      image: mysql:5.7
      restart: always
      ports: 3309:3306
      environment:
        MYSQL_ROOT_PASSWORD: P@ssw0rd1
        MYSQL_DATABASE: cells
        MYSQL_USER: pydio
        MYSQL_PASSWORD: P@ssw0rd
      command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
      volumes:
        - ./data/mysqldir:/var/lib/mysql

