version: '2'

services:
  organizer:
    image: monitorr/monitorr
    restart: always
    container_name: monitorr
    ports:
      - 9008:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ Pacific/Auckland
    networks:
      - default
    volumes:
      - /home/dockers/monitorr/app:/app

networks:
  default:
    external:
      name: docker-network