version: "3"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./config:/config
    ports:
      - 9020:80
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external:
      name: docker-network
