    version: "2"
    services:
      bookstack:
        image: linuxserver/bookstack
        container_name: bookstack
        environment:
          - PUID=1000
          - PGID=1000
          - DB_HOST=192.168.10.42:3036
          - DB_USER=bookstack
          - DB_PASS=B00kstack
          - DB_DATABASE=Bookstackapp
        volumes:
          - ./config:/config
        ports:
          - 9015:80
        restart: unless-stopped
        networks:
          - default