version: "3"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 8001:9117
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external:
      name: docker-network