#Template for Docker Compose Version 3
version: '3'
services:
  Bitwarden_RS:
    image: bitwardenrs/server:alpine
    restart: always
    container_name: Bitwarden
    ports:
        - 8020:8005
    environment:
      - DOMAIN=https://bitwarden.technicalkiwi.com 
      - ADMIN_TOKEN=Hello123
    networks:
      - default
    volumes:
      - ./config:/config

networks:
  default:
    external:
      name: docker-network
