version: "3"
services:

    wikijs:
    image: requarks/wiki:2
    container_name: WikiJS
    depends_on:
      - wikijs-db
    environment:
      DB_TYPE: mariadb
      DB_HOST: 192.168.10.42
      DB_PORT: 3306
      DB_USER: WikiJS
      DB_PASS: W1kiJ3
      DB_NAME: WikiJS-DB
    restart: unless-stopped
    ports:
      - 9015:80
      - 9016:3000
    networks:
      - default

networks:
  default:
    external:
      name: docker-network
