version: '3'
services:
  wikijs:
    image: requarks/wiki:2
    container_name: WikiJS
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_DATABASE}
    restart: unless-stopped
    ports:
      - 9016:80
      - 9015:3000
    networks:
      - default


networks:
  default:
    external:
      name: docker-network

      
