version: "3.9"

# $DOCKERDIR references a location you want to persist data on the machine running docker.

services:
  actual:
    image: kovah/actual-budget-server
    restart: unless-stopped
    container_name: actual
    networks:
      - default
    ports:
      - 5006:5006
    volumes:
      - ./data:/data

networks:
  default:
    external:
      name: docker-network