version: '3'
 
services:
  mayandb:
    image: postgres:10
    container_name: mayan-edms-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: m-pass
      POSTGRES_USER: mayan
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - mayan-bridge
  mayanapp:
    image: mayanedms/mayanedms:3.1.10
    container_name: mayan-edms
    depends_on:
      - mayandb
    links:
      - mayandb:db
    ports:
      - 20201:8000
    environment:
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: db
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: m-pass
      MAYAN_DATABASE_USER: mayan
      MAYAN_DATABASE_CONN_MAX_AGE: 60
    volumes:
      - ./data/scanned_files:/srv/scanned_files
      - ./data/watch_folder:/srv/watch_folder
      - ./data/media:/var/lib/mayan
    networks:
      - mayan-bridge
 
networks:
  mayan-bridge:
    driver: bridge