version: "3"
services:
  mysql:
    image: mysql:5
    container_name: snipe_mysql
    restart: always
    volumes:
      - /home/dockers/snipeit/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Sn1pe1t
      - MYSQL_USER=snipe_usr
      - MYSQL_PASSWORD=Sn1pe1t
      - MYSQL_DATABASE=snipe_it
    ports:
      - 3307:3306
    networks:
      - default


  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - /home/dockers/snipeit/config:/config
    environment:
      - APP_URL=https://asset.cernonz.com
      - MYSQL_PORT_3306_TCP_ADDR=snipe_mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe_it
      - MYSQL_USER=snipe_usr
      - MYSQL_PASSWORD=Sn1pe1t
      - PGID=1000
      - PUID=1000
      - APP_TIMEZONE=Pacific\Auckland
      - APP_LOCALE=en
      - MAIL_PORT_587_TCP_ADDR=
      - MAIL_ENV_FROM_ADDR=Assets@mclarens.co.nz
      - MAIL_ENV_FROM_NAME=Asset_Management
    ports:
      - "9010:80"
    networks:
     - default

networks:
  default:
    external:
      name: docker-network