version: '3'
services:
  Gate-One:
    image: liftoff/gateone
    restart: always
    container_name: Gate-One
    ports:
        - 9022:8000
    networks:
      - default


networks:
  default:
    external:
      name: docker-network
