version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 9025:3000
    environment:
      REDMINE_DB_MYSQL: redmine
      REDMINE_DB_PASSWORD: R3dm1ne

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: R3dm1ne
      MYSQL_DATABASE: redmine
      MYSQL_DATABASE_PASSWORD: R3dm1ne