version: "3"
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
        - ./config:/config
    ports:
      - 8010:3579
    restart: unless-stopped
    networks:
      - defaults

networks: 
  default:
    external:
      name: docker-network
