version: "2"
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
        - /home/dockers/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped