version: "3"
services:

  wikijs-db:
    image: postgres:11-alpine
    container_name: WikiJS-DB
    environment:
      POSTGRES_DB: WikiJS-DB
      POSTGRES_PASSWORD: W1kiJ3
      POSTGRES_USER: WikiJS
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - default

  wikijs:
    image: requarks/wiki:2
    container_name: WikiJS
    depends_on:
      - wikijs-db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: WikiJS
      DB_PASS: W1kiJ3
      DB_NAME: WikiJS-DB
    restart: unless-stopped
    ports:
      - "80:9015"
    networks:
      - default

networks:
  default:
    external:
      name: docker-network