version: "3"
services:

  mysql:
    image: mysql:5
    container_name: Mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Br1scoe3
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./mysql/:/var/lib/msql
      - ./init/:/docker-entrypoint-initdb.d
    ports:
      - 3308:3306
    networks:
      - default

networks:
  default:
    external:
      name: docker-network
