version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 9100:9100
    restart: unless-stopped