version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/dockers/jackett/config:/config
      - /home/dockers/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped