version: "3"
services:
  web:
    build: .
    ports:
      - "8070:3333"
    depends_on:
      - postgres
    networks:
      - default
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - default
    environment:
      POSTGRES_USER: citadel
      POSTGRES_PASSWORD: citadel_test
      POSTGRES_DB: citadel
    volumes:
    - citadel-postgres:/var/lib/postgresql/data

volumes:
  citadel-postgres:
    external: false

networks:
  default:
    external:
      name: docker-network