version: "3"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - UMASK_SET=022 #optional
    volumes:
      - ./config:/config
      - /hdd/Videos/Movies:/movies
      - /hdd/Downloads:/downloads
    ports:
      - 8003:7878
    networks: 
      - default


networks:
    default:
      external:
        name: docker-network