version: '3'
services:
  CloudBeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    container_name: CloudBeaver
    ports:
      - 9090:8978
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Pacific\Auckland
    networks:
      - default
    volumes:
      - ./workspace:/opt/cloudbeaver/workspace


networks:
  default:
    external:
      name: docker-network

