version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_leantime
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: '321.qwerty'
        MYSQL_DATABASE: 'leantime'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: '321.qwerty'
    networks:
      - leantime
    ports:
      - 3306:3306
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
  web:
    image: leantime/leantime:latest
    container_name: leantime
    environment:
        DB_HOST: 10.10.27.90
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: '321.qwerty'
        MYSQL_DATABASE: 'leantime'
    networks:
    - leantime
    ports:
      - "9000:9000"
      - "85:80"
    depends_on:
      - db
networks:
  leantime:
    external:
      name: leantime-net

volumes:
    db_data: {}