version: '3'

services:
  MkDocs:
    image: squidfunk/mkdocs-material
    restart: always
    container_name: "MkDocs"
    ports:
        - 9023:8000
    networks:
      - default
    volumes:
      - ./docs:/docs

networks:
  default:
    external:
      name: docker-network
