version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - JELLYFIN_PublishedServerUrl=192.168.1.202 #optional
    volumes:
      - ./library:/config
      - /nas/tv:/data/tvshows
      - /nas/Movies:/data/movies
      - /nas/Anime:/data/anime
      - /nas/music:/data/music
      - /nas/Comedy:/data/comedy
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external:
      name: docker-network
