---
    version: "2.1"
    services:
      papermerge:
        image: ghcr.io/linuxserver/papermerge
        container_name: papermerge
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Pacific/Auckland
          - REDIS_URL= #optional
        volumes:
          - ./config:/config
          - ./data:/data
        ports:
          - 8000:8000
        restart: unless-stopped