---
version: "2.1"
services:
  emby:
    image: lscr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./library:/config
      - /nas/Anime:/data/anime
      - /nas/tv:/data/tvshows
      - /nas/Movies:/data/movies
      - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8097:8096
      - 8921:8920 #optional
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external:
      name: docker-network