version: '3'

services:
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: ${DB_HOST}
      VIKUNJA_DATABASE_PASSWORD: ${DB_PASS}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: ${DB_USER}
      VIKUNJA_DATABASE_DATABASE: ${DB_NAME}
    volumes: 
      - ./files:/app/vikunja/files
    restart: unless-stopped
    
  frontend:
    image: vikunja/frontend
    restart: unless-stopped
    ports: 
      - 8071:80